### ISSUE TITLE
Balloon for previous edition tiles

### ISSUE THREAD

**Issue by AshV** [TWChennai/geeknight#7]
For previous edition tiles at bottom of home page, can we have edition's topic as title/hover balloon, so without actually navigating user can decide whether to click or not.

In hyderabad geeknight webpage, I was looking for some previous edition now it's painful to navigate to each page and check. That repo is forked from this one so no option to raise issue, that's why submitting here.

Thanks

**Comment by ashokgowtham** [comment]
The GeekNight page has been under redesign and the newer version addresses your concern, you should be able to see the latest version in Chennai's GeekNight page already.
https://twchennai.github.io/geeknight/
I guess the other related sites should soon be updated.

**Comment by AshV** [comment]
New design looks awesome 😀 and addresses may concern too. Thanks
